<?
    include('../consent_settings.php');
    $dbh = init();
    $usernames = [
'tansaku',
'mmosley',
'parkinson2012',
'mirkov_sasa',
'abidmfarooq',
'fernando_',
'trivium',
'msmithnova',
'Mr-Jonze',
'chicoo',
'xp42',
'Sebastian114',
'idfubar',
'Haispdn',
'Tologon',
'pcollet',
'AlbertoRuiz',
'eocarragain',
'AJ_Soares',
'kanmai',
'schemular',
'skyking',
'SamLau',
'premedios',
'tahrisqalli ',
'Mineta',
'ssarrr',
'rbatta',
'_AV',
'_AV',
'pajaja',
'jarepau',
'jshoun01',
'YuanjiSun',
'cm123',
'xaragne',
'ntimsina',
'pixel5011',
'leaonfm',
'BrunnoGoncalves',
'jhanks',
'lumerdiop',
'RyanZE',
'RyanZE',
'SHeinrich',
'samboston',
'balalr92',
'JoelDD',
'France-Nor Brute',
'salerat',
'samcho',
'LDub',
'dashoxha',
'rishikachhawaha',
'rkkamlesh007',
'sledoux',
'Mahi_7838',
'puneethrai',
'madan1988',
'Belethia',
'Madhav M. Patel',
'raun',
'anibalcatamarca',
'kitex',
'mareksuppa',
'anibalcatamarca',
'inbev',
'bluffking',
'DusicaJ',
'omid.mt',
'ekrako',
'jutrera',
'Bermejo',
'joclerc',
'chunkybacon',
'Daniel92',
'RobbieJackson',
'nursultan2010',
'rahulkosarwal',
'rahulkosarwal',
'DEBUDAY',
'vaboro',
'Lawaly',
'gspilio',
'battlewar',
'kush1438',
'ganadini_akshay',
'angarg12',
'schemular',
'zamansaray',
'faillace',
'phildionne',
'jnichols',
'paolope',
'timbortnik',
'mathsaddict',
'VGascon',
'achecopar',
'xaragne',
'rciurlea',
'StankovicsAron',
'gomesluiz',
'hriosm',
'jarlerik',
'pablofullana',
'erintl',
'noamkfir',
'ylevchenko',
'devmgs',
'olpau',
'a_amadou',
'Benjamim',
'Minkowski',
'robsnani',
'tsawan',
'justom',
'4li_Z',
'Vukan',
'nitsnitish7',
'Sugantha Subbiah',
'DaisukeHirata',
'ccosenza',
'giropa832',
'Ashvalatore',
'hmcampos',
'randyfay',
'NinadJaane',
'alexrun',
'siriraavi',
'Nathanael',
'LegionMX'
];

    foreach ($usernames as $username) {
        $stmt = $dbh->prepare('SELECT nextpopuptime,consentedtime,rejectedtime,isadmin FROM consent WHERE username=:username');
        $stmt->execute(array(':username' => $username));
        $result = $stmt->fetch();
        if ($result) {
            $stmt = $dbh->prepare('UPDATE consent SET isadmin=1 WHERE username=:username');
            $stmt->execute(array(':username' => $username));
            echo 'User "' . $username . '" has been made an admin and can access the chat tab and embedded chat freely.';
        } else {
            $stmt = $dbh->prepare('INSERT INTO consent(username,nextpopuptime,consentedtime,rejectedtime,isadmin) VALUES (:username,NULL,NULL,NULL,1)');
            $stmt->execute(array(':username' => $username));
            echo 'User "' . $username . '" has been made an admin and can access the chat tab and embedded chat freely as soon as they complete the consent form.';
        }
    }
?>